# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-github-com-moguimon-viajes.disqus.com'

menu:
- {name: 'Sobre Mi', path: 'menu', url: 'sobremi.html'}
- {name: 'Blog de mis Viajes', path: 'menu', url: 'viajes.html'}
- {name: 'Contacto', path: 'menu', url: 'contacto.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/moguimon'}
- {icon: 'twitter', link: 'https://twitter.com/Tmoguimon'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/feed/'}
- {icon: 'envelope', link: 'mailto:moguimon@gmail.com'}

# Customize site text
pagination:
  next_page: 'Nuevas'
  previous_page: 'Antiguas'

sharing_button_prompt: 'Comparte con tus amigos'

related_posts: 'También puedes ver:'

post_date_prefix: 'Escrito en'
